matrix:
  include:
    - stage: test
      name: test_linux_3_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge lammps jupyter nbconvert pyiron lammps jinja2
        # - pip install --pre --force-reinstall --no-dependencies pyiron 
        # - pip install --force-reinstall --no-dependencies git+https://github.com/pyiron/pyiron.git
        - git clone https://github.com/pyiron/pyiron-resources.git
        - echo -e "[DEFAULT]\nTOP_LEVEL_DIRS = $PWD\nRESOURCE_PATHS = $PWD/pyiron-resources" > ~/.pyiron
        # - wget https://wiki.fysik.dtu.dk/gpaw-files/gpaw-setups-0.9.20000.tar.gz
        # - tar -xzf gpaw-setups-0.9.20000.tar.gz
        # - export GPAW_SETUP_PATH=$PWD/gpaw-setups-0.9.20000
      script:
        - python ci/run.py
