matrix:
  include:
    - stage: test
      name: test_linux_3_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge lammps jupyter nbconvert pyiron jinja2
        - git config --global user.email "${GH_EMAIL}"
        - git config --global user.name "${GH_USER}"
        - git clone https://github.com/pyiron/pyiron-resources.git
        - git clone https://${GH_USER}:${GH_TOKEN}@github.com/thermopot/website.git
        - echo -e "[DEFAULT]\nTOP_LEVEL_DIRS = $PWD\nRESOURCE_PATHS = $PWD/pyiron-resources" > ~/.pyiron
      script:
        - python ci/run.py
        - cd website
        - git add -A
        - git commit -m  "${TRAVIS_COMMIT_MESSAGE}" 
      deploy:
        provider: script
        script: git push
        on:
          branch: master  
